### ISSUE TITLE
Dependency update suggestions with Renovate

### ISSUE THREAD

**Issue by mikaelol** [statnett/image-scanner-operator#127]
Currently, we have Dependabot as the workhorse for suggesting dependency updates, and while it works fine for many types of dependencies, it is not as flexible as e.g. Renovate. It is possible to use both Dependabot and Renovate, or just Renovate.

If we want Renovate, we got three options as far as I can see:

* Install [the Renovate app](https://github.com/apps/renovate) in Statnett org and specify this repository as one of those it should renovate.
* Run Renovate self-hosed as a workflow with the [renovatebot/github-action](https://github.com/renovatebot/github-action). Then we can make the workflow run on a schedule with a cron expression. **NB**: requires a PAT, `GITHUB_TOKEN` does not work, see [token section](https://github.com/renovatebot/github-action#token).
* Run Renovate as a self-hosted GitHub app: https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app

**Comment by erikgb** [comment]
Would you consider option 1 the simplest? I suggest we start with that.

**Comment by mikaelol** [comment]
Yes, option 1 would be the simplest.

If we go with the option of keeping Dependabot I may suggest disabling Renovate (by config file) for Go updates and GitHub-actions updates, so we don't get double up on those.
