### ISSUE TITLE
Fine-tune PR titles in Renovate PRs

### ISSUE THREAD

**Issue by erikgb** [statnett/image-scanner-operator#173]
I was too fast merging https://github.com/statnett/image-scanner-operator/pull/171, as this should have been classified as a user-facing change and appeared in the changelog.

Can Renovate be configured to use a different PR title depending on the suggested change? As we can do with Dependabot, ref.

https://github.com/statnett/image-scanner-operator/blob/main/.github/dependabot.yml#L9-L11

**Comment by mikaelol** [comment]
That is possible, more fine-grained than I initially thought (by using `semanticCommitType` in a `packageRule` with a matcher). We can set PR title based on many attributes of a dependency, e.g. what type of dependency it is (docker, golang etc.), name of the dependency (either perfect match or regex match), pattern of package path (e.g. everything in `test/` folder should have a specific PR title).

Trivy (`ghcr.io/aquasecurity/trivy`) is a candidate, it is a docker dependency so we can match it on either docker or name. But we don't want docker dependencies like https://github.com/statnett/image-scanner-operator/pull/158 to be `build`, so maybe not based docker?
