### ISSUE TITLE
Golangci-lint cache input key is wrong on re-runs

### ISSUE THREAD

**Issue by padlar** [statnett/image-scanner-operator#5]
When I reran the `golangci-lint` job, there was a problem loading the cache

```
  /usr/bin/tar: ../../../go/pkg/mod/github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb_test_proto/Makefile: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb_test.go: Cannot open: File exists
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
  Cache not found for input keys: golangci-lint.cache-2766-764367f7551edc6ee1cd40c0c794ec829fc93f91, golangci-lint.cache-2766-
  Prepared env in 6800ms
```

job - https://github.com/statnett/image-scanner-operator/actions/runs/3845788279/jobs/6550500816

**Comment by mikaelol** [comment]
@padlar , is this still a problem? I tried to [rerun a `golangci-lint` job now](https://github.com/statnett/image-scanner-operator/actions/runs/5399170911/jobs/9806072840), and it worked. Is there any other way than rerunning a lint job that can reproduce this?

I notice that in the issue you created upstream got the label `question`, meaning *Further information requested*, but I can't see what kind of information is requested, do you know?

**Comment by padlar** [comment]
Looks like this has been fixed in the underlying github actions pkg https://github.com/actions/toolkit/pull/1353. We can close this issue and probably update https://github.com/golangci/golangci-lint-action/issues/640 with our observation?

**Comment by mikaelol** [comment]
Sounds like a plan to me :-)

**Comment by erikgb** [comment]
This issue seems to have been fixed now.
