### ISSUE TITLE
Image scanner is oscillating when two pods from same workload have different image in the containerStatuses

### ISSUE THREAD

**Issue by bendikp** [statnett/image-scanner-operator#85]
A workload with multiple pods (i.e. ReplicaSet) can potentially get different `image` in the `containerStatuses` in the Pod specification.

This leads to a oscillating behavior in the image scanner, where the `spec.tag` is constantly changing.

**Comment by erikgb** [comment]
Could the same happen to the image name? WDYT?

**Comment by bendikp** [comment]
Don't know tbh.

**Comment by bendikp** [comment]
Others have seen the same: https://github.com/kubernetes/kubernetes/issues/74081

**Comment by erikgb** [comment]
We could address a potential issue with the image name in a follow-up PR. Since we rely on the image to scan to be present on the node, we should probably use the name from pod status.
