### ISSUE TITLE
Cron job to prune our GHCR should run regularly

### ISSUE THREAD

**Issue by erikgb** [statnett/image-scanner-operator#97]
Somehow the cron job is never triggered, ref. https://github.com/statnett/image-scanner-operator/actions/workflows/clean-ghcr.yaml

**Comment by erikgb** [comment]
This still doesn't work, ref. https://github.com/statnett/image-scanner-operator/actions/workflows/clean-ghcr.yaml

**Comment by bendikp** [comment]
"0 0 1 * *" => monthly
"0 1 * * *" => daily
